baseURL: "https://ctrl-freelance.github.io/"
theme: "up-business-theme"
languageCode: "en-us"

title: "ctrl freelance"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "ctrl freelance"
  description: "We specialise in providing services from translation to designing websites for our clients."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "350 Hoe Street, London, United Kingdom. E17 9PX"
  contact:
    - "support@ctrl-freelance.com"
    - ""

  copyright: "Â© 2024 ctrl freelance All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Book a call"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
